### ISSUE TITLE
USER STORY: Shopping Cart

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#11]
As a **shopper**, I can **add items to cart, view items in my cart and adjust the quantity before checkout** so that **I can review and modify my order**

# **Acceptance Criteria:**
   - User can click on "Add To Cart" button and get a confirmation message displayed
   - Users can navigate to a cart page.
   - The cart page displays selected items and their quantities.
   - Users can adjust the quantity of individual items.
    
# **Tasks:**
   - [x] Display a pop-up window with the items being added to the cart
   - [x] Create a cart page.
   - [x] Display selected items and quantities on the cart page.
   - [x] Implement the ability to adjust the quantity of items.
