### ISSUE TITLE
USER STORY: Add Products

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#19]
As a **site admin**  I can **add products to the catalog** so that **I can expand and update the product offerings**

# **Acceptance Criteria:**
- Admin can log in with special administrative privileges.
- Admin can access a product management page.
- Admin can add a new product with details.

# **Tasks:**
- [x] Implement admin authentication with special privileges.
- [x] Create a page for product management.
- [x] Implement functionality to add a new product.
