### ISSUE TITLE
USER STORY: Edit/Update Products

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#20]
As a **site admin** I can **edit/update existing products on the webiste** so that **I can keep product information accurate**

# **Acceptance Criteria:**
- Admin can log in with special administrative privileges.
- Admin can access a product management page.
- Admin can edit/update existing product information.

# **Tasks:**
- [x] Implement admin authentication with special privileges.
- [x] Create a page for product management.
- [x] Implement functionality to edit/update existing product information.
