### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#21]
As a **site admin** I can **delete products from the catalog** so that **I can manage the product offerings effectively**

# **Acceptance Criteria:**
- Admin can log in with special administrative privileges.
- Admin can access a product management page.
- Admin can delete a product from the catalog.

# **Tasks:**
- [x] Implement admin authentication with special privileges.
- [x] Create a page for product management.
- [x] Implement functionality to delete a product.
