### ISSUE TITLE
USER STORY: Contact Page

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#22]
As a **user** I can **fill out the contact form and send a message** so that **I can communicate with the site administrators**

# **Acceptance Criteria:**
- Users can access a contact form.
- Users can enter their name, email and message.
- A confirmation message is displayed after successfully submitting the form.

# **Tasks:**
- [x] Implement a contact form.
- [x] Design and implement the contact form view.
- [x] Handle form submission and display a confirmation message.
