### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#23]
As a **user** I can **subscribe to the newsletter** so that **I can receive updates and promotions**

# **Acceptance Criteria:**
- Users can find a newsletter subscription option.
- Users can enter their email to subscribe.
- A confirmation message is displayed after successful subscription.

# **Tasks:**
- [x] Implement a newsletter subscription option.
- [x] Design and implement the newsletter subscription view.
- [x] Handle subscription requests and display a confirmation message.
