### ISSUE TITLE
USER STORY: Comments

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#24]
As a **user** I can **leave comments under a certain product** so that **I can share my thoughts**

# **Acceptance Criteria:**
- Users can navigate to a product details page.
- Users can view existing comments.
- Users can leave a new comment.
- Comments are displayed chronologically.

# **Tasks:**
- [x] Implement a comment section on the product details page.
- [x] Design and implement the comment section view.
- [x] Implement functionality to leave a comment.
