### ISSUE TITLE
USER STORY: SEO Optimization

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#25]
As a **site admin** I can **make the website SEO-optimized** so that **it ranks higher in search engine results**

# **Acceptance Criteria:**
- Implement meta tags for pages.
- Optimize image alt attributes.
- Create a sitemap and submit it to search engines.

# **Tasks:**
- [x] Implement meta tags for pages.
- [x] Optimize image alt attributes.
- [x] Create and implement a sitemap.
