### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/blissbowl#6]
As a **user** I can **see a home page with featured products, categories, comments and newsletter** so that **I can discover new and exciting items**.

# **Acceptance Criteria:**
  - Users are redirected to the home page upon login.
  - Featured products, categories, comments and newsletter are displayed on the home page.
  
#  **Tasks:**
  - [x] Design and implement the home page.
  - [x] Implement redirection to the home page upon login.
  - [x] Display products, categories, comments and newsletter on the home page.
